In [1]:
import tensorflow as tf

In [2]:
layer = tf.keras.layers.Dense(100)

layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [3]:
layer(tf.zeros([10, 5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [4]:
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.19996104, -0.02625889, -0.21922058,  0.04577041, -0.12562382,
         -0.46058875,  0.20283073,  0.59233564,  0.2616284 ,  0.38155228],
        [ 0.15010518,  0.47771674, -0.2670975 , -0.52111435,  0.31134248,
         -0.23287681, -0.31352744,  0.4927587 ,  0.00152284,  0.11819941],
        [-0.13843212,  0.2002973 ,  0.40063316,  0.6058313 , -0.4524819 ,
          0.5561729 ,  0.37768656, -0.32781923,  0.37883347, -0.5038324 ],
        [ 0.02369499, -0.2878114 , -0.57143235, -0.4478801 ,  0.3273961 ,
         -0.42993546,  0.39069337,  0.25974005, -0.14329356, -0.20518738],
        [ 0.52704793,  0.46901864,  0.5412521 , -0.07448292, -0.34658042,
          0.4261865 , -0.56964356,  0.55193883, -0.5345044 ,  0.3175428 ]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [5]:
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.19996104, -0.02625889, -0.21922058,  0.04577041, -0.12562382,
         -0.46058875,  0.20283073,  0.59233564,  0.2616284 ,  0.38155228],
        [ 0.15010518,  0.47771674, -0.2670975 , -0.52111435,  0.31134248,
         -0.23287681, -0.31352744,  0.4927587 ,  0.00152284,  0.11819941],
        [-0.13843212,  0.2002973 ,  0.40063316,  0.6058313 , -0.4524819 ,
          0.5561729 ,  0.37768656, -0.32781923,  0.37883347, -0.5038324 ],
        [ 0.02369499, -0.2878114 , -0.57143235, -0.4478801 ,  0.3273961 ,
         -0.42993546,  0.39069337,  0.25974005, -0.14329356, -0.20518738],
        [ 0.52704793,  0.46901864,  0.5412521 , -0.07448292, -0.34658042,
          0.4261865 , -0.56964356,  0.55193883, -0.5345044 ,  0.3175428 ]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [6]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super().__init__()
    
    self.num_outputs = num_outputs
    
  def build(self, input_shape):
    self.kernel = self.add_weight("kernel", shape=[int(input_shape[-1]), self.num_outputs])
    
  def call(self, _input):
    return tf.matmul(_input, self.kernel)
  
layer = MyDenseLayer(10)

In [7]:
layer(tf.zeros([10, 5]));

In [8]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer/kernel:0']


In [9]:
layer.kernel

<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.48366582,  0.27682972,  0.00869602,  0.38519615, -0.26974913,
        -0.08354414, -0.11645579, -0.14894679,  0.5525195 ,  0.02588147],
       [ 0.15863985, -0.29266906, -0.0775997 ,  0.20527065, -0.6065272 ,
        -0.4212393 , -0.18353528,  0.14279896, -0.4224925 , -0.3886699 ],
       [ 0.2895441 ,  0.39864415,  0.6071928 ,  0.32575083, -0.6045897 ,
        -0.543849  , -0.3101166 ,  0.37308103,  0.37571317,  0.16804713],
       [-0.00881577, -0.5174538 , -0.2961787 , -0.30796543, -0.5177786 ,
         0.14217967,  0.4026286 ,  0.4029811 ,  0.10726267,  0.30419195],
       [ 0.49200362, -0.5951167 , -0.4109873 , -0.5033786 , -0.27576125,
        -0.3044932 ,  0.19112313, -0.29112107, -0.34969285, -0.564424  ]],
      dtype=float32)>

In [22]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name="")
    f1, f2, f3 = filters
    
    self.conv2a = tf.keras.layers.Conv2D(f1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()
    
    self.conv2b = tf.keras.layers.Conv2D(f2, kernel_size, padding="same")
    self.bn2b = tf.keras.layers.BatchNormalization()
    
    self.conv2c = tf.keras.layers.Conv2D(f3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()
    
  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)
    
    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)
    
    x = self.conv2c(x)
    x = self.bn2c(x, training=training)
    
    x += input_tensor
    return tf.nn.relu(x)
  
block = ResnetIdentityBlock(1, [1, 2, 3])

In [23]:
block(tf.zeros([1, 2, 3, 3]));

In [24]:
block.layers

In [25]:
len(block.variables)

18

In [26]:
block.summary()

Model: "resnet_identity_block_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_9 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization_9 (Batch multiple                  4         
_________________________________________________________________
conv2d_10 (Conv2D)           multiple                  4         
_________________________________________________________________
batch_normalization_10 (Batc multiple                  8         
_________________________________________________________________
conv2d_11 (Conv2D)           multiple                  9         
_________________________________________________________________
batch_normalization_11 (Batc multiple                  12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
______________________________________________

In [20]:
my_seq = tf.keras.Sequential([
  tf.keras.layers.Conv2D(1, (1, 1), input_shape=(None, None, 3)),
  tf.keras.layers.BatchNormalization(),
  tf.keras.layers.Conv2D(2, 1, padding="same"),
  tf.keras.layers.BatchNormalization(),
  tf.keras.layers.Conv2D(3, (1, 1)),
  tf.keras.layers.BatchNormalization()
])

my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [21]:
my_seq.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, None, None, 1)     4         
_________________________________________________________________
batch_normalization_6 (Batch (None, None, None, 1)     4         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, None, None, 2)     4         
_________________________________________________________________
batch_normalization_7 (Batch (None, None, None, 2)     8         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, None, None, 3)     9         
_________________________________________________________________
batch_normalization_8 (Batch (None, None, None, 3)     12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
___________________________________________________________